version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.1.32
    container_name: car-rental-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:0.4.15
    container_name: car-rental-chromadb
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: car-rental-postgres
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: car-rental-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
  postgres_data: