services:
  ollama:
    image: ollama/ollama:0.1.32
    container_name: car-rental-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    pull_policy: missing
    networks:
      - ai-network

  chromadb:
    image: chromadb/chroma:0.4.15
    container_name: car-rental-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped
    pull_policy: missing
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local
  ollama_data:
    driver: local